project:
  type: website
  output-dir: docs
  
execute:
  freeze: auto

format:
  html:
    theme: 
      - flatly
      - styles.scss
    
    toc: true
    toc-depth: 5
    toc-expand: 1
    toc-title: Table of content
    toc-location: left
    
    citations-hover: true
    footnotes-hover: true
    reference-location: margin

website:
  title: "OutbreakTools training"
  favicon: images/icon.png
  repo-url: https://github.com/epicentre-msf/obt-training
  
  # Options
  page-navigation: true
  back-to-top-navigation: true

  
  # Navbar
  navbar:
    search: true
    logo: images/icon.png
    
    # left:
    #  - text: About
    #    href: index.qmd
        
    right: 
      - text: Module 1
        menu:
          - text: Module presentation
            href: module_1/m1_objectives.qmd
          - text: Introduction to OutbreakTools
            href: module_1/m1_intro.qmd
          - text: Tutorial
            href: module_1/m1_tutorial.qmd
          
      
      - text: Module 2
        menu:
          - text: Module presentation
            href: module_2/m2_objectives.qmd
          - text: Introduction to the setup file
            href: module_2/m2_intro.qmd
          - text: Tutorial
            href: module_2/m2_tutorial.qmd
          
      - text: How to
        menu:
          - text: Unblock files
            href: how_to/unblock_files.qmd
          - text: Download geobase
            href: how_to/download_geobase.qmd
          - text: Get a linelist template
            href: how_to/get_template.qmd
          - text: Export data to dashboard
            href: how_to/export_data_dashboard.qmd
          - text: Use the GeoHelper
            href: how_to/use_geohelper.qmd
            
      - text: Reference
        menu: 
          - text: Ribbons
            href: reference/ribbons.qmd
        
        
    tools:
      - icon: github
        text: Source Code
        href: https://github.com/epicentre-msf/obt-training

  # Side navigation bar
  # sidebar:
  #   contents: auto

  # Footer
  page-footer:
    left: Developed by [![](images/epicentre.png){fig-alt="Epicentre logo" width=65px}](https://epicentre.msf.org/)
    right: This website is built with {{< fa heart title="a heart" >}}, [{{< fa brands github title="GitHub octocat logo" >}}](https://github.com){target=_blank}, [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank}

