---
title: "Use the GeoHelper"
---

#### GeoHelper {#sec-geo-helper}

The **GeoHelper** is a popup window that helps you entering geographic data surch as the origin of the patient or the name of the facility (if the ["hf" control was used for the variable](../reference/dictionary_sheet.qmd#sec-geo-data)). It is mostly used to enter data on the patient data sheet, but it is also useful on the Spatio-Temporal analysis sheet.

To use it, place your cursor in a "geo" or "hf" column (you can recognise them thanks to the orange headers), in the *admin 1 level*. Click on the "Geohelper" button, or hit the shortcut `Ctrl + Shift + G`. It opens a window, with several tabs, depending on whether you are in a "geo" (described by four visible columns) or in "hf" (decribed by one isible column).

If you are in a "geo" section, you will have three tabs that you can use to select administrative levels.

- **Cascade**: select the admin levels with cascading menus, by selecting one admin level after the other, starting from the highest one. 
- **Search**: search by typing the name (needs at least 3 letters)
- **History**: quickly find a previous entry entered through the GeoHelper (does not work for data entered using the regular cascading dropdowns).

Once the location has been found, select it and click on “OK”.