---
title: "Module presentation and objectives"
---

This training will teach you how to use OutbreakTools (OBT) tools to generate an OBT linelist from a dictionary. You will then learn how to modify a setup to perform common tasks, such as adding a specific export of data for a MoH, and adding some analyses that you need in the field.

**Tentative length: 3h**

## Objectives

After this training, you should be able to:

-	Grasp the use of the different OutbreakTools files
-	Find the most recent version of the tools, as well as the documentation
-	Describe the functions of the different setup sheets
-	Modify an existing setup to:

    - Add new categorical and calculated variables
    - Add a new export
    - Add new analyses
-	Use this setup and the designer to generate a new linelist

## Prerequistes

You should have completed the first module on [OutbreakTools linelists](../module_1/m1_objectives.qmd), or be very familiar with the OBT linelists and their functions (optional variables, custom dropdown, analyses…)

## Content of the training

The training will be based on a mix of slides and exercises. The exercise will be based on a common situation: a linelist already exists, but needs to be customised a bit. You want to add an export for your country, and some additional analyses.

